<?php
/**
 * generatetelemetrydata.php
 *
 * Route responsible for generating a random XML tree - circuit board message
 * Used to generate messages in order to sent them using ee m2m website
 *
 * @author Adam Machowczyk, Dominik Michalski
 */

use \Psr\Http\Message\ServerRequestInterface as Request;
use \Psr\Http\Message\ResponseInterface as Response;

$app->any(
    '/generatetelemetrydata',
    function (Request $request, Response $response) use ($app) {
        //the method to create new data
        $telemetry_data = generateTelemetryData($app);

        //append the data to an xml skeleton
        $telemetry_data_xml = appendToXml($telemetry_data);

        return $this->view->render(
            $response,
            'display_results.html.twig',
            [
                'css_path' => CSS_PATH,
                'landing_page' => LANDING_PAGE,
                'initial_input_box_value' => null,
                'page_title' => APP_NAME,
                'page_heading_1' => APP_NAME,
                'page_heading_2' => 'Result',
                'switches' => $telemetry_data['switches'],
                'fan' => $telemetry_data['fan'],
                'heater' => $telemetry_data['heater'],
                'keypad' => $telemetry_data['keypad'],
                'id' => $telemetry_data['unique_id'],
                'tree' => $telemetry_data_xml,
                'session' => $_SESSION
            ]
        );
    }
);

function generateTelemetryData($app)
{
    $telemetry_data = [];
    $number_of_switches = 4;

    //switches
    for ($i = 0; $i < $number_of_switches; $i++) {
        $random_number = rand(1, 20);
        $telemetry_data['switches'][$i] = $random_number > 10 ? 1 : 0;
    }

    //fan
    $random_number = rand(1, 20);
    $telemetry_data['fan'] = $random_number > 10 ? "forward" : "reverse";

    //heater - generate temperature between -26 and 26 degree celsius
    $random_temperature_number = (rand(0, 52) - 26) . ',' . rand(1, 99);
    $telemetry_data['heater'] = $random_temperature_number;

    //keypad
    $random_keypad_number = rand(0, 9); //keypad holds numbers from 0-9
    $telemetry_data['keypad'] = $random_keypad_number;

    //unique id, generated by using getToken() function
    $wrapper = $app->getContainer()->get('DatabaseWrapper');
    $id = $wrapper -> getToken(10);
    $telemetry_data['unique_id'] = $id;

    return $telemetry_data;
}

function appendToXml($telemetry_data, $format = 0)
{
    $xmlTree = "";
    if ($format == 1) {
        $xmlTree = "<telemetrydata>";

        $xmlTree .= "<telemetrydata_switches>";
        $xmlTree .= "<telemetrydata_switch>" . $telemetry_data['switches'][0] . "</telemetrydata_switch>";
        $xmlTree .= "<telemetrydata_switch>" . $telemetry_data['switches'][1] . "</telemetrydata_switch>";
        $xmlTree .= "<telemetrydata_switch>" . $telemetry_data['switches'][2] . "</telemetrydata_switch>";
        $xmlTree .= "<telemetrydata_switch>" . $telemetry_data['switches'][3] . "</telemetrydata_switch>";
        $xmlTree .= "</telemetrydata_switches>";

        $xmlTree .= "<telemetrydata_fan>" . $telemetry_data['fan'] . "</telemetrydata_fan>";
        $xmlTree .= "<telemetrydata_temperature>" . $telemetry_data['heater'] . "</telemetydata_temperature>";
        $xmlTree .= "<telemetrydata_keypad>" . $telemetry_data['keypad'] . "</telemetrydata_keypad>";

        $xmlTree .= "</telemetrydata>";
    } else {
        $xmlTree = "<t>";

        $xmlTree .= "<ss>";
        $xmlTree .= "<s>" . $telemetry_data['switches'][0] . "</s>";
        $xmlTree .= "<s>" . $telemetry_data['switches'][1] . "</s>";
        $xmlTree .= "<s>" . $telemetry_data['switches'][2] . "</s>";
        $xmlTree .= "<s>" . $telemetry_data['switches'][3] . "</s>";
        $xmlTree .= "</ss>";

        $xmlTree .= "<f>" . $telemetry_data['fan'] . "</f>";
        $xmlTree .= "<tp>" . $telemetry_data['heater'] . "</tp>";
        $xmlTree .= "<tk>" . $telemetry_data['keypad'] . "</tk>";
        $xmlTree .= "<id>" . $telemetry_data['unique_id'] . "</id>";

        $xmlTree .= "</t>";
    }

    return $xmlTree;
}
